/**
   ht-div-uint64.c

   A hash table with generic hash keys and generic elements. The 
   implementation is based on a division method for hashing into upto  
   > 2^63 slots (last entry in the PRIMES array; the upper range requiring 
   > 2^64 addresses) and a chaining method for resolving collisions. Due to
   chaining, the number of keys and elements that can be inserted is not
   limited by the hash table implementation.
   
   The load factor of a hash table is the expected number of keys in a slot 
   under the simple uniform hashing assumption, and is upper-bounded by the 
   alpha parameter. The alpha parameter does not provide an upper bound 
   after the maximum count of slots in a hash table is reached.

   A hash key is an object within a contiguous block of memory (e.g. a basic 
   type, array, struct). An element is an object within a contiguous or
   noncontiguous block of memory.
*/

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include "ht-div-uint64.h"
#include "dll.h"
#include "utilities-mem.h"
#include "utilities-rand-mod.h"

/**
   An array of primes in the increasing order, approximately doubling in 
   magnitude, that are not too close to the powers of 2 and 10 to avoid 
   hashing regularities due to the structure of data. The prime numbers
   were generated by applying miller-rabin-uint64.
*/
static const uint64_t PRIMES[54] = {1543, 3119,
				    6211, 12343,
				    23981, 48673,
				    88843, 186581,
				    377369, 786551,
				    1483331, 3219497,
				    6278177, 12538919,
				    25166719, 51331771,
				    112663669, 211326637,
				    412653239, 785367311,
				    1611612763, 3221225479,
				    6442451311, 12881269573,
				    25542415651, 51713873269,
				    119353582331, 211752305939,
				    417969972941, 817459404833,
				    1621224516137, 3253374675631,
				    6594291673951, 13349461912351,
				    26380589320219, 52758518323127,
				    118691918825723, 214182177768131,
				    419189283369523, 832735214133421,
				    1672538661088171, 3158576518771277,
				    6692396525189279, 13791536538127669,
				    26532115188884581, 55793289756397591,
				    113545326073368661, 217449629757435791,
				    431794910914467367, 841413987972987841,
				    1755714234418853843, 3358355678469146183,
				    6884922145916737697, 15769474759331449193U};
static const int PRIMES_UINT32_COUNT = 22;
static const int PRIMES_COUNT = 54;
static size_t CMP_KEY_SIZE;

static uint64_t hash(const ht_div_uint64_t *ht, const void *key);
static void ht_grow(ht_div_uint64_t *ht);
static void copy_reinsert(ht_div_uint64_t *ht, const dll_node_t *node);
static int cmp_key(const void *a, const void *b);

/**
   Initializes a hash table. 
   ht          : a pointer to a preallocated block of size 
                 sizeof(ht_div_uint64_t).
   key_size    : size of a key object
   elt_size    : - size of an element object, if the element object is
                 within a contiguous memory block,
                 - size of a pointer to an element object, if the element
                 object is within a noncontiguous memory block
   alpha       : > 0.0, a load factor upper bound.
   free_elt    : - if an element is within a contiguous memory block,
                 as reflected by elt_size, and a pointer to the element is 
                 passed as elt in ht_div_uint64_insert, then the element is
                 fully copied into a hash table, and NULL as free_elt is
                 sufficient to delete the element,
                 - if an element is an object within a noncontiguous memory
                 block, and a pointer to a pointer to the element is passed
                 as elt in ht_div_uint64_insert, then the pointer to the
                 element is copied into the hash table, and an element-specific
                 free_elt, taking a pointer to a pointer to an element as its
                 parameter, is necessary to delete the element
*/
void ht_div_uint64_init(ht_div_uint64_t *ht,
                        size_t key_size,
	                size_t elt_size,
			float alpha,
	                void (*free_elt)(void *)){
  ht->count_ix = 0;
  ht->key_size = key_size;
  ht->elt_size = elt_size;
  ht->count = PRIMES[ht->count_ix];
  ht->num_elts = 0;
  ht->alpha = alpha;
  ht->key_elts = malloc_perror(ht->count * sizeof(dll_node_t *));
  for (uint64_t i = 0; i < ht->count; i++){
    dll_init(&ht->key_elts[i]);
  }
  ht->free_elt = free_elt;
  CMP_KEY_SIZE = key_size;
}

/**
   Inserts a key and an associated element into a hash table. If the key is
   in the hash table, associates the key with the new element. The key and
   elt parameters are not NULL.
*/
void ht_div_uint64_insert(ht_div_uint64_t *ht,
			  const void *key,
			  const void *elt){
  uint64_t ix;
  dll_node_t **head = NULL, *node = NULL;
  //grow hash table if E[# keys in a slot] > alpha
  while ((float)ht->num_elts / ht->count > ht->alpha &&
	 ht->count_ix < PRIMES_COUNT - 1){
    ht_grow(ht);
  }
  ix = hash(ht, key);
  head = &ht->key_elts[ix];
  node = dll_search_key(head, key, cmp_key);
  if (node == NULL){
    dll_prepend(head, key, elt, ht->key_size, ht->elt_size);
    ht->num_elts++;
  }else{
    dll_delete(head, node, ht->free_elt);
    dll_prepend(head, key, elt, ht->key_size, ht->elt_size);
  }   
}

/**
   If a key is present in a hash table, returns a pointer to its associated 
   element, otherwise returns NULL. The key parameter is not NULL.
*/
void *ht_div_uint64_search(const ht_div_uint64_t *ht, const void *key){
  dll_node_t *node = dll_search_key(&ht->key_elts[hash(ht, key)],
				     key,
				     cmp_key);
  if (node == NULL){
    return NULL;
  }else{
    return node->elt;
  }
}

/**
   Removes a key and the associated element from a hash table by copying 
   the element into a block of size elt_size pointed to by elt. If the key is
   not in the hash table, leaves the block pointed to by elt unchanged.
   The key and elt parameters are not NULL.
*/
void ht_div_uint64_remove(ht_div_uint64_t *ht, const void *key, void *elt){
  dll_node_t **head = &ht->key_elts[hash(ht, key)];
  dll_node_t *node = dll_search_key(head, key, cmp_key);
  if (node != NULL){
    memcpy(elt, node->elt, ht->elt_size);
    //if an element is noncontiguous, only the pointer to it is deleted
    dll_delete(head, node, NULL);
    ht->num_elts--;
  }
}

/**
   If a key is present in a hash table, deletes the key and its associated 
   element according free_elt. The key parameter is not NULL.
*/
void ht_div_uint64_delete(ht_div_uint64_t *ht, const void *key){
  dll_node_t **head = &ht->key_elts[hash(ht, key)];
  dll_node_t *node = dll_search_key(head, key, cmp_key);
  if (node != NULL){
    dll_delete(head, node, ht->free_elt);
    ht->num_elts--;
  }
}

/**
   Frees a hash table and leaves a block of size sizeof(ht_div_uint64_t)
   pointed to by the ht parameter.
*/
void ht_div_uint64_free(ht_div_uint64_t *ht){
  for (uint64_t i = 0; i < ht->count; i++){
    dll_free(&ht->key_elts[i], ht->free_elt);
  }
  free(ht->key_elts);
  ht->key_elts = NULL;
}

/** Helper functions */

/**
   Maps a hash key to a slot index in a hash table with a division method. 
*/
static uint64_t hash(const ht_div_uint64_t *ht, const void *key){
  if (ht->count_ix < PRIMES_UINT32_COUNT){
    //fast_mem_mod_uint32 is faster than fast_mem_mod_uint64
    return (uint64_t)fast_mem_mod_uint32(key,
					 (uint64_t)ht->key_size,
					 (uint32_t)ht->count);
  }else{
    return fast_mem_mod_uint64(key,
			       (uint64_t)ht->key_size,
			       ht->count);
  } 
}

/**
   Increases the size of a hash table by the difference between the ith and 
   (i + 1)th prime numbers in the PRIMES array. Makes no changes if the last
   prime number in the PRIMES array was reached.
*/
static void ht_grow(ht_div_uint64_t *ht){
  uint64_t prev_count = ht->count;
  dll_node_t **prev_key_elts = ht->key_elts;
  dll_node_t **head = NULL;
  //if the largest size is reached, alpha is not a bound for expectation
  if (ht->count_ix == PRIMES_COUNT - 1) return;
  ht->count_ix++;
  ht->count = PRIMES[ht->count_ix];
  ht->num_elts = 0;
  ht->key_elts = malloc_perror(ht->count * sizeof(dll_node_t *));
  for (uint64_t i = 0; i < ht->count; i++){
    head = &ht->key_elts[i];
    dll_init(head);
  }
  for (uint64_t i = 0; i < prev_count; i++){
    head = &prev_key_elts[i];
    while (*head != NULL){
      copy_reinsert(ht, *head);
      //if an element is noncontiguous, only the pointer to it is deleted
      dll_delete(head, *head, NULL);
    }
  }
  free(prev_key_elts);
  prev_key_elts = NULL;
  head = NULL;
}

/**
   Reinserts a copy of a node into a new hash table during an ht_grow 
   operation. In contrast to ht_div_uint64_insert, no search is performed.
*/
static void copy_reinsert(ht_div_uint64_t *ht, const dll_node_t *node){
  dll_prepend(&ht->key_elts[hash(ht, node->key)],
	      node->key,
	      node->elt,
	      ht->key_size,
	      ht->elt_size);
  ht->num_elts++;   
}

/**
   Compares two hash keys.
*/
static int cmp_key(const void *a, const void *b){
  return memcmp(a, b, CMP_KEY_SIZE);
}
